// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQyiP3f536SJMlCEMQVTkHl2WSJoui1E',
    appId: '1:46403069869:web:53d5176af2f904bd54e324',
    messagingSenderId: '46403069869',
    projectId: 'sanpo-26e4c',
    authDomain: 'sanpo-26e4c.firebaseapp.com',
    storageBucket: 'sanpo-26e4c.appspot.com',
    measurementId: 'G-NQKVLGS8W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5L6WGNV8uiV-IGYEQjWnMWhYoF6iPpY',
    appId: '1:46403069869:android:7fb49f5581cc63ad54e324',
    messagingSenderId: '46403069869',
    projectId: 'sanpo-26e4c',
    storageBucket: 'sanpo-26e4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7pmmm3wo1CACg1Sqiq0mllIT1q0kh7ek',
    appId: '1:46403069869:ios:58a6fcb91cb233e154e324',
    messagingSenderId: '46403069869',
    projectId: 'sanpo-26e4c',
    storageBucket: 'sanpo-26e4c.appspot.com',
    iosBundleId: 'com.example.sanpo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7pmmm3wo1CACg1Sqiq0mllIT1q0kh7ek',
    appId: '1:46403069869:ios:58a6fcb91cb233e154e324',
    messagingSenderId: '46403069869',
    projectId: 'sanpo-26e4c',
    storageBucket: 'sanpo-26e4c.appspot.com',
    iosBundleId: 'com.example.sanpo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXQyiP3f536SJMlCEMQVTkHl2WSJoui1E',
    appId: '1:46403069869:web:40d5af069ad449ee54e324',
    messagingSenderId: '46403069869',
    projectId: 'sanpo-26e4c',
    authDomain: 'sanpo-26e4c.firebaseapp.com',
    storageBucket: 'sanpo-26e4c.appspot.com',
    measurementId: 'G-6MTL3B1LNF',
  );

}